version: "3"

services:

  nginx:
    image: nginx:stable-alpine
    volumes:
      - "./index.html:/usr/share/nginx/html/index.html:ro"
    networks:
      - backend

  proxy:
    image: nginx:stable-alpine
    links:
      - nginx
    ports:
      - "80:80"
    volumes:
      - "./proxy.conf:/etc/nginx/nginx.conf:ro"
    networks:
      - backend
      - frontend

networks:
  backend:
    internal: true
  frontend:
